pub mod albums;
pub mod analytics;
pub mod artists;
#[cfg(target_os = "linux")]
pub mod bluetooth;
pub mod browse;
pub mod devices;
pub mod docs;
pub mod dsp;
pub mod genres;
pub mod player;
pub mod playlists;
pub mod rsql;
pub mod saved_playlists;
pub mod search;
pub mod settings;
pub mod smart_playlists;
pub mod system;
pub mod tracks;
