#!/usr/bin/env bash
#
# Publish the shared native package `rockbox_ffi_nif` (bindings/erlang) to Hex
# via rebar3, from a workstation. BOTH the Elixir (rockbox_ex_ffi) and Gleam
# (rockbox_ffi) bindings depend on this package for their native code, so it
# must be published FIRST, before publish-elixir.sh / publish-gleam.sh.
#
# The multi-megabyte NIF .so files are NOT bundled in the Hex tarball (they
# exceed Hex's 8 MB limit across platforms). They are built + uploaded to the
# `erlang-v<version>` GitHub release by the `bindings-erlang-release.yml`
# workflow; the loader (src/rockbox_ffi_nif.erl) downloads the matching one on
# first use and verifies it against priv/rockbox_ffi_nif.manifest. This script:
#   1. downloads the release NIFs to a temp dir (only to hash them),
#   2. writes priv/rockbox_ffi_nif.manifest (repo, tag, one sha256 per triple),
#   3. removes any .so from priv/ so they aren't published, then `rebar3 hex publish`.
#
# Hex publishing is deliberately NOT done in CI: Hex auth is interactive.
# Authenticate first:  rebar3 hex user auth   (or export HEX_API_KEY=...)
#
# Usage:
#   bindings/scripts/publish-erlang.sh [--tag erlang-vX.Y.Z] [--repo owner/repo] [--dry-run]
#
# The tag defaults to erlang-v<version> read from rockbox_ffi_nif.app.src.

set -euo pipefail
COMMON_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=_release_common.sh
. "$COMMON_DIR/_release_common.sh"
ROOT="$(cd "$COMMON_DIR/../.." && pwd)"
ERLANG_DIR="$ROOT/bindings/erlang"

parse_common_args "$@"
[ ${#REST[@]} -eq 0 ] || { echo "unknown argument: ${REST[0]}" >&2; exit 2; }

command -v rebar3 >/dev/null 2>&1 || { echo "error: rebar3 not found — https://rebar3.org" >&2; exit 1; }
command -v gh     >/dev/null 2>&1 || { echo "error: gh (GitHub CLI) required — https://cli.github.com" >&2; exit 1; }

# Resolve repo from origin (gh may pick a different default with multiple remotes).
if [ -z "$REPO" ]; then
  url="$(git -C "$COMMON_DIR" remote get-url origin 2>/dev/null || true)"; url="${url%.git}"
  case "$url" in
    git@github.com:*)       REPO="${url#git@github.com:}" ;;
    ssh://git@github.com/*) REPO="${url#ssh://git@github.com/}" ;;
    https://github.com/*)   REPO="${url#https://github.com/}" ;;
  esac
  [ -n "$REPO" ] || { echo "error: could not derive repo from origin; pass --repo owner/repo" >&2; exit 1; }
fi

# Resolve tag: --tag, else erlang-v<version-from-app.src> (matches the workflow).
if [ -z "$TAG" ]; then
  VERSION="$(sed -n 's/.*{vsn, *"\([^"]*\)".*/\1/p' "$ERLANG_DIR/src/rockbox_ffi_nif.app.src" | head -1)"
  [ -n "$VERSION" ] || { echo "error: could not read {vsn, ...} from rockbox_ffi_nif.app.src; pass --tag" >&2; exit 1; }
  TAG="erlang-v$VERSION"
fi

echo "== rockbox_ffi_nif -> Hex =="
echo "Repo:    $REPO"
echo "Release: $TAG"
[ "$DRY" -eq 1 ] && echo "Mode:    DRY RUN (nothing will be pushed)"
echo

# Download EVERY release NIF to a TEMP dir purely to compute its checksum — the
# NIFs are downloaded on first use, never bundled, so we cover all platforms
# (macOS, Linux, FreeBSD, NetBSD) via the wildcard.
mkdir -p "$ERLANG_DIR/priv"
# Never bundled — drop any .so left in priv/ so `rebar3 hex publish` can't sweep
# them into the (8 MB-capped) tarball.
rm -f "$ERLANG_DIR/priv"/rockbox_ffi_nif*.so
NIFTMP="$(mktemp -d)"
trap 'rm -rf "$NIFTMP"' EXIT
echo "  downloading all release NIFs to hash them (macOS, Linux, FreeBSD, NetBSD)"
download_assets "$NIFTMP" 'rockbox_ffi_nif-*.so' || true
shopt -s nullglob
sos=("$NIFTMP"/rockbox_ffi_nif-*.so)
[ ${#sos[@]} -gt 0 ] || {
  echo "error: no rockbox_ffi_nif-*.so found in release $TAG." >&2
  echo "       Run the bindings-erlang-release.yml workflow first (it uploads them)." >&2
  exit 1
}

# sha256 helper — shasum on macOS, sha256sum elsewhere.
sha256_of() {
  if command -v shasum >/dev/null 2>&1; then shasum -a 256 "$1" | awk '{print $1}'
  else sha256sum "$1" | awk '{print $1}'; fi
}

# Write the checksum manifest the loader (src/rockbox_ffi_nif.erl) reads.
MANIFEST="$ERLANG_DIR/priv/rockbox_ffi_nif.manifest"
{
  echo "%% Generated by publish-erlang.sh — do not edit by hand."
  echo "%% The loader downloads the matching rockbox_ffi_nif-<triple>.so from"
  echo "%% GitHub release $TAG on first use and verifies it against these sums."
  echo "{repo, \"$REPO\"}."
  echo "{tag, \"$TAG\"}."
  for so in "${sos[@]}"; do
    triple="$(basename "$so" .so)"; triple="${triple#rockbox_ffi_nif-}"
    echo "{checksum, \"$triple\", \"$(sha256_of "$so")\"}."
  done
} > "$MANIFEST"
echo "  -> priv/rockbox_ffi_nif.manifest"
sed 's/^/     /' "$MANIFEST"

cd "$ERLANG_DIR"
# `rebar3 hex publish` packages the source (per rebar.config's {hex,{files,...}})
# and uploads it. --yes skips the interactive confirmation; Hex auth is still
# read from `rebar3 hex user auth` / HEX_API_KEY.
run rebar3 hex publish --yes
echo "Done."
