#!/usr/bin/env bash
#
# Publish the Gleam package to Hex from a local machine (correct OTP + interactive
# Hex auth — `gleam publish` can't do Hex 2FA in CI).
#
# The NIFs are NOT bundled in the Hex package — 4 platforms exceed Hex's 8 MB
# compressed-tarball limit even stripped. Instead the loader downloads the
# matching rockbox_ffi_nif-<triple>.so from the `gleam-v<version>` GitHub release
# on first use and verifies it against a checksum manifest. This script:
#   1. downloads the release NIFs to a temp dir (only to hash them),
#   2. writes priv/rockbox_ffi_nif.manifest (repo, tag, one sha256 per triple),
#   3. removes any .so from priv/ so they aren't published, then `gleam publish`.
# The NIFs themselves are built + uploaded to the release by the
# `bindings-gleam-release.yml` GitHub Actions workflow.
#
# Authenticate first:  gleam hex authenticate   (or export HEXPM_API_KEY=...)
#
# Usage:
#   bindings/scripts/publish-gleam.sh [--tag gleam-vX.Y.Z] [--repo owner/repo] [--dry-run]
#
# The tag defaults to gleam-v<version> read from gleam.toml.

set -euo pipefail
COMMON_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=_release_common.sh
. "$COMMON_DIR/_release_common.sh"
ROOT="$(cd "$COMMON_DIR/../.." && pwd)"
GLEAM_DIR="$ROOT/bindings/gleam"

parse_common_args "$@"
[ ${#REST[@]} -eq 0 ] || { echo "unknown argument: ${REST[0]}" >&2; exit 2; }

command -v gleam >/dev/null 2>&1 || { echo "error: gleam not found — https://gleam.run" >&2; exit 1; }
command -v gh    >/dev/null 2>&1 || { echo "error: gh (GitHub CLI) required — https://cli.github.com" >&2; exit 1; }

# Resolve repo from origin (gh may pick a different default with multiple remotes).
if [ -z "$REPO" ]; then
  url="$(git -C "$COMMON_DIR" remote get-url origin 2>/dev/null || true)"; url="${url%.git}"
  case "$url" in
    git@github.com:*)       REPO="${url#git@github.com:}" ;;
    ssh://git@github.com/*) REPO="${url#ssh://git@github.com/}" ;;
    https://github.com/*)   REPO="${url#https://github.com/}" ;;
  esac
  [ -n "$REPO" ] || { echo "error: could not derive repo from origin; pass --repo owner/repo" >&2; exit 1; }
fi

# Resolve tag: --tag, else gleam-v<version-from-gleam.toml> (matches the workflow).
if [ -z "$TAG" ]; then
  VERSION="$(sed -n 's/^version *= *"\(.*\)"/\1/p' "$GLEAM_DIR/gleam.toml" | head -1)"
  [ -n "$VERSION" ] || { echo "error: could not read version from gleam.toml; pass --tag" >&2; exit 1; }
  TAG="gleam-v$VERSION"
fi

echo "== Gleam -> Hex =="
echo "Repo:    $REPO"
echo "Release: $TAG"
[ "$DRY" -eq 1 ] && echo "Mode:    DRY RUN (nothing will be pushed)"
echo

# Download EVERY release NIF to a TEMP dir purely to compute its checksum — the
# NIFs are downloaded on first use, never bundled, so size no longer matters and
# we cover all platforms (macOS, Linux, FreeBSD, NetBSD) via the wildcard.
# Tolerate a missing/empty release so the guard below gives an actionable message.
mkdir -p "$GLEAM_DIR/priv"
# Never bundled — drop any .so left in priv/ so `gleam publish` can't sweep them
# into the (8 MB-capped) tarball.
rm -f "$GLEAM_DIR/priv"/rockbox_ffi_nif*.so
NIFTMP="$(mktemp -d)"
trap 'rm -rf "$NIFTMP"' EXIT
echo "  downloading all release NIFs to hash them (macOS, Linux, FreeBSD, NetBSD)"
download_assets "$NIFTMP" 'rockbox_ffi_nif-*.so' || true
shopt -s nullglob
sos=("$NIFTMP"/rockbox_ffi_nif-*.so)
[ ${#sos[@]} -gt 0 ] || {
  echo "error: no rockbox_ffi_nif-*.so found in release $TAG." >&2
  echo "       Run the bindings-gleam-release.yml workflow first (it uploads them)." >&2
  exit 1
}

# sha256 helper — shasum on macOS, sha256sum elsewhere.
sha256_of() {
  if command -v shasum >/dev/null 2>&1; then shasum -a 256 "$1" | awk '{print $1}'
  else sha256sum "$1" | awk '{print $1}'; fi
}

# Write the checksum manifest the loader (src/rockbox_ffi_nif.erl) reads.
MANIFEST="$GLEAM_DIR/priv/rockbox_ffi_nif.manifest"
{
  echo "%% Generated by publish-gleam.sh — do not edit by hand."
  echo "%% The loader downloads the matching rockbox_ffi_nif-<triple>.so from"
  echo "%% GitHub release $TAG on first use and verifies it against these sums."
  echo "{repo, \"$REPO\"}."
  echo "{tag, \"$TAG\"}."
  for so in "${sos[@]}"; do
    triple="$(basename "$so" .so)"; triple="${triple#rockbox_ffi_nif-}"
    echo "{checksum, \"$triple\", \"$(sha256_of "$so")\"}."
  done
} > "$MANIFEST"
echo "  -> priv/rockbox_ffi_nif.manifest"
sed 's/^/     /' "$MANIFEST"

cd "$GLEAM_DIR"
# `gleam publish` uploads the package and its HexDocs. `gleam docs publish`
# afterwards is idempotent and refreshes HexDocs even when the version already
# exists (re-run docs without a version bump).
run gleam publish --yes
run gleam docs publish
echo "Done."
