[package]
name = "rockbox-rocksky"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
lofty = "0.21.1"
dirs = "6.0.0"
prost = "0.13.2"
rockbox-library = { path = "../library" }
reqwest = { version = "0.12.5", features = [
  "rustls-tls-native-roots",
  "json",
  "multipart"
], default-features = false }
rocksky-sdk = { version = "0.11.2", features = ["remote-player"] }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
toml = "0.8.19"
sha256 = "1.5.0"
tokio = { version = "1.36.0", features = ["full"] }
tonic = "0.12.3"
tonic-reflection = "0.12.3"
tonic-web = "0.12.3"
rustls = { version = "0.23", default-features = false, features = ["ring", "logging", "std", "tls12"] }
tracing = { workspace = true }

[build-dependencies]
tonic-build = "0.12.3"
