[package]
edition = "2021"
name = "rockbox-graphql"
version = "0.1.0"

[dependencies]
actix-cors = "0.7.0"
actix-files = "0.6.6"
actix-web = "4.13.0"
anyhow = "1.0.87"
async-graphql = "7.2.1"
async-graphql-actix-web = "7.2.1"
chrono = {version = "0.4.38", features = ["serde"]}
cuid = "1.3.3"
futures = "0.3.30"
futures-channel = "0.3.31"
futures-util = "0.3.31"
md5 = "0.7.0"
once_cell = "1.20.2"
owo-colors = "4.1.0"
tracing = {workspace = true}
reqwest = {version = "0.12.5", features = ["rustls-tls-native-roots", "json"], default-features = false}
rockbox-library = {path = "../library"}
rockbox-jellyfin = {path = "../jellyfin"}
rockbox-kodi = {path = "../kodi"}
rockbox-navidrome = {path = "../navidrome"}
rockbox-plex = {path = "../plex"}
rockbox-upnp = {path = "../upnp"}
rockbox-playlists = {path = "../playlists"}
rockbox-rocksky = {path = "../rocksky"}
rockbox-settings = {path = "../settings"}
rockbox-typesense = {path = "../typesense"}
rockbox-fts5 = {path = "../fts5", optional = true}
rockbox-sys = {path = "../sys"}
rockbox-types = {path = "../types"}
rockbox-webui = {path = "../../webui"}
serde = "1.0.210"
serde_json = "1.0.128"
slab = "0.4.9"
sqlx = {version = "0.8.2", features = ["runtime-tokio", "tls-rustls", "sqlite", "chrono", "derive", "macros"]}
tokio = {version = "1.36.0", features = ["full"]}

[features]
default = []
fts5 = ["dep:rockbox-fts5"]

[target.'cfg(target_os = "linux")'.dependencies]
rockbox-bluetooth = {path = "../bluetooth"}
